version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
